### ISSUE TITLE
Script loading users, but not projects. Users can't log in as themself.

### ISSUE THREAD

**Issue by arkag** [devurandom/phabricator-ldap-sync#2]
After running the script all users are imported. Sadly, when trying to log in, it prompts the user to make an account and then tells the user that their name and email are taken. It doesn't allow them to just log in.

Projects are also not being created. 

I don't really know how to debug this because it is not failing anymore.

**Comment by ghost** [comment]
> After running the script all users are imported. Sadly, when trying to log in, it prompts the user to make an account and then tells the user that their name and email are taken. It doesn't allow them to just log in.

I need more information to help you.

First: What authentication provider do you use? Built-in LDAP? RemoteUser and webserver authentication?

> Projects are also not being created.

The script never creates projects. It just syncs the members of those projects you specify via the "LDAP DN" field.

**Comment by urzds** [comment]
> Projects are also not being created.

The script never creates projects. It just syncs the members of those projects you specify (via the "LDAP DN" field).

**Comment by arkag** [comment]
Ahhh. Okay. We must have misunderstood the script then. Regardless, we're using built in LDAP.

**Comment by ghost** [comment]
Just to make sure I understand you correctly:
- After running the sync-ldap script, users which are also present in LDAP are unable to login?
- And they were able to login before you ran this script?

You are sure you setup LDAP authentication correctly? I.e. it worked correctly at some point in time?

I am surprised, because this script should never ever create any users - it does not even contain any logic to do so... The only thing it does is compute the sets `phab-project-members \ ldap-group-members` and `ldap-group-members \ phab-project-members` and then add/remove project members based on that, which should never make any LDAP users known to Phabricator, if they were not known to it before...

**Comment by arkag** [comment]
I’ll have to look at this on Monday, sorry. As far as I know, yes. That’s what
happened. But I could be gravely mistaken. I’ll update you after the weekend.
Thanks for all the help so far.

On Fri, Feb 26, 2016 at 5:00 PM, Dennis Schridde notifications@github.com
wrote:
Just to make sure I understand you correctly:
- After running the sync-ldap script, users which are also present in LDAP are
  unable to login?
- And they were able to login before you ran this script?

You are sure you setup LDAP authentication correctly? I.e. it worked correctly
at some point in time?

I am surprised, because this script should never ever create any users - it does
not even contain any logic to do so... The only thing it does is compute the
sets phab-project-members \ ldap-group-members and ldap-group-members \ phab-project-members and then add/remove project members based on that, which should never make any
LDAP users known to Phabricator, if they were not known to it before...

—
Reply to this email directly or view it on GitHub
[https://github.com/uhd-urz/phabricator-sync-ldap/issues/2#issuecomment-189518255] .[https://github.com/notifications/beacon/AGb-cn35tnZpWl0eXY58YCa3vc9vKJ1Gks5poNCOgaJpZM4HkMOd.gif]

**Comment by ghost** [comment]
Were you able to reproduce the issue?

**Comment by arkag** [comment]
Just got into work. Give me a bit.

**Comment by arkag** [comment]
Just created a new container and installed Phabricator with my configurations. After running the script, the error I got before doesn't seem to exist. It's possible it was because I was using the original script that you forked from first and then tried using your script. Thanks for the help.
